blank_issues_enabled: false
contact_links:
  - name: Landscapes Reimagined Hub Discord
    url: https://discord.gg/quenZthXgy
    about: Join the Discord for quick questions, discussion, and support.
